#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-File-Copy-Link
Version  : 0.140
Release  : 15
URL      : https://cpan.metacpan.org/authors/id/R/RM/RMBARKER/File-Copy-Link-0.140.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RM/RMBARKER/File-Copy-Link-0.140.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libf/libfile-copy-link-perl/libfile-copy-link-perl_0.140-2.debian.tar.xz
Summary  : 'extension for replacing a link by a copy of the linked file'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-File-Copy-Link-bin = %{version}-%{release}
Requires: perl-File-Copy-Link-license = %{version}-%{release}
Requires: perl-File-Copy-Link-man = %{version}-%{release}
Requires: perl-File-Copy-Link-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
File-Copy-Link version 0.14
===========================
The distribution File-Copy-Link includes the modules
File::Spec::Link and File::Copy::Link and the script
copylink.  They include routines to read and copy links.

%package bin
Summary: bin components for the perl-File-Copy-Link package.
Group: Binaries
Requires: perl-File-Copy-Link-license = %{version}-%{release}

%description bin
bin components for the perl-File-Copy-Link package.


%package dev
Summary: dev components for the perl-File-Copy-Link package.
Group: Development
Requires: perl-File-Copy-Link-bin = %{version}-%{release}
Provides: perl-File-Copy-Link-devel = %{version}-%{release}
Requires: perl-File-Copy-Link = %{version}-%{release}

%description dev
dev components for the perl-File-Copy-Link package.


%package license
Summary: license components for the perl-File-Copy-Link package.
Group: Default

%description license
license components for the perl-File-Copy-Link package.


%package man
Summary: man components for the perl-File-Copy-Link package.
Group: Default

%description man
man components for the perl-File-Copy-Link package.


%package perl
Summary: perl components for the perl-File-Copy-Link package.
Group: Default
Requires: perl-File-Copy-Link = %{version}-%{release}

%description perl
perl components for the perl-File-Copy-Link package.


%prep
%setup -q -n File-Copy-Link-0.140
cd %{_builddir}
tar xf %{_sourcedir}/libfile-copy-link-perl_0.140-2.debian.tar.xz
cd %{_builddir}/File-Copy-Link-0.140
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/File-Copy-Link-0.140/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-File-Copy-Link
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-File-Copy-Link/1d05ddeaeb5ca9b5fda3d0db44ee6ed6c9ae2661
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/copylink

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/File::Copy::Link.3
/usr/share/man/man3/File::Spec::Link.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-File-Copy-Link/1d05ddeaeb5ca9b5fda3d0db44ee6ed6c9ae2661

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/copylink.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.30.3/File/Copy/Link.pm
/usr/lib/perl5/vendor_perl/5.30.3/File/Spec/Link.pm
